Repository
ThesplumCoder/sisgan-server pull request #4
Opened 2024-04-30 03:09 UTC by SorryIWinxX

Ejemplos de como hacer los repositorios

2024-04-30 20:54 UTC, ThesplumCoder requested changes
Documentar en general todo el código. Revisar los comentarios.

2024-04-30 20:54 UTC, ThesplumCoder commented on pom.xml
Retirar la dependencia de PostgresSQL, para mantener solo un conector con base de datos; además, retirar los `source` y `target`, que hacen que el compilador no trabaje en la versión LTS de Java.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/CattleRepository.java
No olvidar documentar las firmas de los métodos y la clase.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/FarmerRepository.java
En la variable `farmerCrudRepository`, ¿no falta el `@Autowired`? ¿Qué utilidad tiene envolver `findAll` en `getAll`?

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Cattle.java
> +@Table(name = "cattles")
El nombre de las tablas está en mayúscula, pero en la notación aparece en minúscula.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Cattle.java
> +public class Cattle {
Falta documentación de la clase.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Cattle.java
> +    private Date birthDate;
No utilizar `Date` porque la misma API lo desaconseja en favor del uso de `LocalDate`.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Cattle.java
> +    private Float weight;
Estos atributos no están mapeados con la BD.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Driver.java
> +@Entity
Con `@Entity` el JPA se asume que se está mapeando una entidad de BD, pero esta clase propiamente no lo es, ¿está probado

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/InternalMovementGuide.java
> +@Table(name = "internal_movement_guides")
Nombre de la tabla no coincide con `name`.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/InternalMovementGuide.java
> +    private String destination;
Falta de anotación de mapeo.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Lot.java
> +@Table(name="lots")
No coincide nombre de tabla con `name`.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Lot.java
> +    private String name;
¿Por qué este atributo está aquí?

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/Rol.java
> +@Table(name = "Roles")
Nombre de la tabla no coincide con el nombre en BD.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/User.java
> +public abstract class User {
Al ser abstracta no se puede instanciar, ¿funciona?

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/User.java
> +    private String password;
Falta de anotación de mapeo.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/User.java
> +    private String email;
Falta de anotación de mapeo.

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/java/com/uis/sisgan/persistence/entity/User.java
> +    private List<Rol> roles;
¿Por qué esto aquí?

2024-04-30 20:54 UTC, ThesplumCoder commented on src/main/resources/application.properties
> +spring.datasource.url=jdbc:postgresql://localhost:5432/sisgan_server
No cambie la BD, ya habíamos acordado que iba a ser MariaDB, o por lo menos no lo haga arbitrariamente.

2024-05-01 00:07 UTC, SorryIWinxX commented on src/main/java/com/uis/sisgan/persistence/entity/Cattle.java
> +@Table(name = "cattles")
eso no importa

2024-05-02 19:16 UTC, ThesplumCoder reviewed
Revisado y modificado los archivos de parametrizaciones y tablas, para que no se mezclen ocn la rama.

2024-05-02 19:16 UTC, ThesplumCoder approved these changes, later dismissed

2024-05-02 19:22 UTC, merged